global using CustomLibrary.EFCore.Extensions;
global using FluentValidation;
global using Hellang.Middleware.ProblemDetails;
global using Microsoft.AspNetCore.Mvc;
global using NET6CustomLibrary.Extensions;
global using NET6CustomLibrary.Swagger;
global using Sample.API.Controllers.Common;
global using Sample.API.Extensions;
global using System.Net.Mime;
